external/libecc: Remove -ffreestanding
This causes issues when FreeBSD cross-builds pkg for a different
architecture (e.g., building for powerpc64 from amd64) using a
non-default sysroot:

--- ec_params.pico ---
In file included from /build/obj/bsd/src/bsd/dev/powerpc.powerpc64/tmp/usr/include/inttypes.h:33:
/build/obj/bsd/src/bsd/dev/powerpc.powerpc64/tmp/usr/include/sys/stdint.h:48:24: error: typedef redefinition with different types ('__int_fast8_t' (aka 'int') vs 'int8_t' (aka 'signed char'
))
   48 | typedef __int_fast8_t           int_fast8_t;
      |                                 ^
/pkg/llvm19/lib/clang/19/include/stdint.h:280:24: note: previous definition is here
  280 | typedef __int_least8_t int_fast8_t;
      |                        ^